export enum StorageLocationStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  MAINTENANCE = 'MAINTENANCE',
  FULL = 'FULL',
  RESTRICTED = 'RESTRICTED',
  EXPIRED = 'EXPIRED',
  TEMPERATURE_CONTROLLED = 'TEMPERATURE_CONTROLLED',
  CLIMATE_CONTROLLED = 'CLIMATE_CONTROLLED',
  QUARANTINE = 'QUARANTINE',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
}
