export enum DENTAL_PROCEDURE_TYPE {
  CONSULTATION = 'consultation',
  CLEANING = 'cleaning',
  FILLING = 'filling',
  EXTRACTION = 'extraction',
  ROOT_CANAL = 'root_canal',
  CROWN = 'crown',
  BRIDGE = 'bridge',
  IMPLANT = 'implant',
  ORTHODONTIC = 'orthodontic',
  WHITENING = 'whitening',
  SCALING = 'scaling',
  POLISHING = 'polishing',
  FLUORIDE_TREATMENT = 'fluoride_treatment',
  SEALANT = 'sealant',
  VENEER = 'veneer',
  DENTURE = 'denture',
  SURGERY = 'surgery',
  EMERGENCY = 'emergency',
}
