export enum TOOTH_CONDITION {
  HEALTHY = 'healthy',
  CAVITY = 'cavity',
  FILLING = 'filling',
  CROWN = 'crown',
  ROOT_CANAL = 'root_canal',
  EXTRACTION = 'extraction',
  IMPLANT = 'implant',
  MISSING = 'missing',
  FRACTURE = 'fracture',
  WORN = 'worn',
  DECAY = 'decay',
  ABSCESS = 'abscess',
  SENSITIVITY = 'sensitivity',
  STAIN = 'stain',
  PLAQUE = 'plaque',
  TARTAR = 'tartar',
}
