FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY .env ./

RUN npm install 

COPY apps/api-gateway apps/api-gateway
COPY libs libs

RUN npm cache clean --force

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app /app

CMD ["npm", "run", "start:gateway"]
